# Generated by Django 5.0.9 on 2026-07-09 16:34

import accounts.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('login_phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('kyc_rejection_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=(accounts.mixins.AuthenticatableAccountMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BusinessOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghana_card_number', models.CharField(max_length=30, unique=True)),
                ('ghana_card_front_image', models.ImageField(upload_to='ghana_cards/')),
                ('ghana_card_back_image', models.ImageField(upload_to='ghana_cards/')),
                ('gps_address', models.CharField(max_length=20)),
                ('business_contact_phone', models.CharField(max_length=20)),
                ('is_formal', models.BooleanField(default=False)),
                ('business_reg_certificate', models.FileField(blank=True, null=True, upload_to='business_reg_certificates/')),
                ('tin', models.CharField(blank=True, max_length=30, null=True)),
                ('payout_bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payout_bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payout_bank_account_name', models.CharField(blank=True, max_length=150, null=True)),
                ('payout_momo_network', models.CharField(blank=True, max_length=20, null=True)),
                ('payout_momo_number', models.CharField(blank=True, max_length=20, null=True)),
                ('payout_momo_name', models.CharField(blank=True, max_length=150, null=True)),
                ('default_payout_method', models.CharField(choices=[('bank', 'Bank'), ('momo', 'Mobile Money')], max_length=10)),
                ('payout_verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=10)),
                ('business_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.businessowner')),
            ],
        ),
    ]
