# Generated by Django 5.0.9 on 2026-07-10 13:35

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_seed_zones_manage_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessownerprofile',
            name='business_reg_certificate',
            field=models.FileField(blank=True, null=True, upload_to='business_reg_certificates/', validators=[accounts.validators.validate_document_content_type]),
        ),
        migrations.AlterField(
            model_name='businessownerprofile',
            name='ghana_card_back_image',
            field=models.ImageField(upload_to='ghana_cards/', validators=[accounts.validators.validate_image_content_type]),
        ),
        migrations.AlterField(
            model_name='businessownerprofile',
            name='ghana_card_front_image',
            field=models.ImageField(upload_to='ghana_cards/', validators=[accounts.validators.validate_image_content_type]),
        ),
    ]
