# Generated by Django 5.0.9 on 2026-07-13 18:38

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_businessownerprofile_business_reg_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessownerprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessownerprofile',
            name='business_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='businessownerprofile',
            name='default_payout_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank'), ('momo', 'Mobile Money')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='businessownerprofile',
            name='ghana_card_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='ghana_cards/', validators=[accounts.validators.validate_image_content_type]),
        ),
        migrations.AlterField(
            model_name='businessownerprofile',
            name='ghana_card_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='ghana_cards/', validators=[accounts.validators.validate_image_content_type]),
        ),
        migrations.AlterField(
            model_name='businessownerprofile',
            name='ghana_card_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='businessownerprofile',
            name='gps_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
