# Generated by Django 5.0.9 on 2026-07-15 13:30

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_seed_reviews_moderate_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='customer_avatars/', validators=[accounts.validators.validate_image_content_type]),
        ),
    ]
