# Generated by Django 5.0.9 on 2026-07-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_seed_event_pricing_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessownerprofile',
            name='business_kind',
            field=models.CharField(blank=True, choices=[('product', 'Product'), ('service', 'Service')], max_length=10, null=True),
        ),
    ]
