# Generated by Django 5.0.9 on 2026-07-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessowner',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessowner',
            name='suspension_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='suspension_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
