# Generated by Django 5.0.9 on 2026-07-17 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_seed_users_manage_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessowner',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessowner',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_business_owners', to='accounts.staffuser'),
        ),
        migrations.AddField(
            model_name='businessownerprofile',
            name='address_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessownerprofile',
            name='address_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessownerprofile',
            name='address_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_verified_profiles', to='accounts.staffuser'),
        ),
    ]
