# Generated by Django 5.0.9 on 2026-07-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_seed_reviews_re_review_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='extra_permissions',
            field=models.ManyToManyField(blank=True, related_name='granted_to_staff', to='accounts.permission'),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='revoked_permissions',
            field=models.ManyToManyField(blank=True, related_name='revoked_from_staff', to='accounts.permission'),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
