# Generated by Django 5.0.9 on 2026-07-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_seed_field_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('marketing', 'Marketing'), ('support', 'Support'), ('scout', 'Scout'), ('delivery_manager', 'Delivery Manager'), ('dispatch', 'Dispatch')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='ScoutAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('visited', 'Visited')], default='assigned', max_length=10)),
                ('address_confirmed', models.BooleanField(blank=True, null=True)),
                ('corrected_address', models.CharField(blank=True, max_length=20)),
                ('business_legitimate', models.BooleanField(blank=True, null=True)),
                ('details_correct', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('visited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scout_assignments_made', to='accounts.staffuser')),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_assignments', to='accounts.businessowner')),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_assignments', to='accounts.staffuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='scoutassignment',
            constraint=models.UniqueConstraint(fields=('business_owner', 'scout'), name='unique_scout_per_business'),
        ),
    ]
