# Generated by Django 5.2.18 on 2026-10-07 19:50

from django.db import migrations, models


def forwards(apps, schema_editor):
    apps.get_model("accounts", "Role").objects.filter(name="admin").update(name="operations")


def backwards(apps, schema_editor):
    apps.get_model("accounts", "Role").objects.filter(name="operations").update(name="admin")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_update_users_permission_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('operations', 'Operations'), ('accountant', 'Accountant'), ('marketing', 'Marketing'), ('support', 'Support'), ('scout', 'Scout'), ('delivery_manager', 'Delivery Manager'), ('dispatch', 'Dispatch')], max_length=20, unique=True),
        ),
        migrations.RunPython(forwards, backwards),
    ]
