# Generated by Django 5.2.18 on 2026-10-07 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_rename_admin_role_to_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_reports', to='accounts.staffuser'),
        ),
        migrations.CreateModel(
            name='RoleInviteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.role')),
                ('inviter_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_rules', to='accounts.role')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('inviter_role', 'invitee_role'), name='unique_role_invite_rule')],
            },
        ),
    ]
