# Generated by Django 5.2.18 on 2026-10-08 02:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_seed_calls_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=64, unique=True)),
                ('device_label', models.CharField(blank=True, default='', max_length=120)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('two_factor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, choices=[('signed_out', 'Signed out'), ('ended', 'Ended from another device'), ('signed_out_everywhere', 'Signed out of every device by a Super Admin'), ('suspended', 'Account suspended'), ('deactivated', 'Account deactivated'), ('password_reset', 'Password reset'), ('idle', '30 minutes without activity'), ('expired', '12-hour limit reached')], default='', max_length=30)),
                ('sudo_until', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.staffuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['staff', 'revoked_at'], name='accounts_st_staff_i_f39efd_idx')],
            },
        ),
    ]
