# Generated by Django 5.0.9 on 2026-07-15 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_seed_reviews_moderate_permission'),
        ('billing', '0006_alter_transaction_status'),
        ('events', '0002_event_capacity_eventrsvp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_method', models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical')], default='digital', max_length=10)),
                ('quantity_total', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=24, unique=True)),
                ('delivery_method', models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('escrow_status', models.CharField(choices=[('held', 'Held'), ('released', 'Released')], default='held', max_length=10)),
                ('escrow_held_at', models.DateTimeField(auto_now_add=True)),
                ('escrow_released_at', models.DateTimeField(blank=True, null=True)),
                ('escrow_override_note', models.CharField(blank=True, default='', max_length=500)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_checkins', to='accounts.staffuser')),
                ('escrow_released_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_overrides', to='accounts.staffuser')),
                ('purchased_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.customer')),
                ('refunded_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_refunds', to='accounts.staffuser')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.eventtickettype')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='billing.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventtickettype',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_ticket_type_name_per_event'),
        ),
    ]
