# Generated by Django 5.0.9 on 2026-07-15 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_seed_orders_manage_delivery_permission'),
        ('events', '0003_eventtickettype_ticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.PositiveIntegerField(choices=[(7, '7 days'), (15, '15 days'), (30, '30 days'), (60, '60 days'), (90, '90 days')], unique=True)),
                ('live_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pending_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proposed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_pricing_proposals', to='accounts.staffuser')),
            ],
            options={
                'ordering': ['duration_days'],
            },
        ),
    ]
