# Generated by Django 5.0.9 on 2026-07-17 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_seed_reviews_re_review_permission'),
        ('events', '0005_seed_event_pricing_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_events', to='accounts.staffuser'),
        ),
    ]
