# Generated by Django 5.2.18 on 2026-10-07 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0034_seed_calls_permissions'),
        ('staff_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=3)),
                ('channel', models.CharField(choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('visit', 'Visit')], default='phone', max_length=10)),
                ('counterpart_type', models.CharField(choices=[('customer', 'Customer'), ('business_owner', 'Business owner'), ('guest', 'Guest'), ('other', 'Other')], max_length=20)),
                ('counterpart_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('counterpart_name', models.CharField(blank=True, default='', max_length=150)),
                ('counterpart_phone', models.CharField(blank=True, default='', max_length=20)),
                ('related_type', models.CharField(blank=True, default='', max_length=50)),
                ('related_id', models.CharField(blank=True, default='', max_length=64)),
                ('related_label', models.CharField(blank=True, default='', max_length=200)),
                ('purpose', models.CharField(max_length=40)),
                ('outcome', models.CharField(choices=[('connected', 'Connected'), ('no_answer', 'No answer'), ('busy', 'Busy'), ('voicemail', 'Voicemail'), ('wrong_number', 'Wrong number'), ('promised_to_pay', 'Promised to pay'), ('callback_requested', 'Callback requested')], max_length=20)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follow_up_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_log', to='staff_tasks.task')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_logs', to='accounts.staffuser')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['staff', '-started_at'], name='calls_calll_staff_i_ce2223_idx'), models.Index(fields=['related_type', 'related_id'], name='calls_calll_related_ede2e9_idx')],
            },
        ),
    ]
