# Generated by Django 5.2.18 on 2026-10-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='counterpart_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('business_owner', 'Business owner'), ('prospect', 'Prospect'), ('guest', 'Guest'), ('other', 'Other')], max_length=20),
        ),
    ]
