# Generated by Django 5.2.18 on 2026-10-08 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0038_seed_reports_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=5)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('returned', 'Returned')], default='draft', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('system_snapshot', models.JSONField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, default='')),
                ('blockers', models.TextField(blank=True, default='')),
                ('plan_next', models.JSONField(blank=True, default=list)),
                ('plan_results', models.JSONField(blank=True, default=list)),
                ('linked_targets', models.JSONField(blank=True, default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('similarity', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_reviewed', to='accounts.staffuser')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='accounts.staffuser')),
            ],
            options={
                'ordering': ['-period_start', '-id'],
                'indexes': [models.Index(fields=['staff', 'status'], name='reports_sta_staff_i_160f42_idx'), models.Index(fields=['period', 'period_start'], name='reports_sta_period_85f35d_idx')],
                'constraints': [models.UniqueConstraint(fields=('staff', 'period', 'period_start'), name='unique_staff_report_period')],
            },
        ),
    ]
