# Generated by Django 5.2.18 on 2026-10-08 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_seed_reports_permission'),
        ('reports', '0002_trigram_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', models.JSONField(default=dict)),
                ('format', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Being prepared'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], default='queued', max_length=8)),
                ('file_name', models.CharField(blank=True, default='', max_length=120)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to='accounts.staffuser')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
