# Generated by Django 5.2.18 on 2026-10-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffreport',
            name='snapshot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
