# Generated by Django 5.0.9 on 2026-07-16 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0020_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('kyc_approved', 'KYC approved'), ('kyc_rejected', 'KYC rejected'), ('kyc_needs_approval', 'KYC needs approval'), ('listing_approved', 'Listing approved'), ('listing_rejected', 'Listing rejected'), ('listing_needs_moderation', 'Listing needs moderation'), ('event_approved', 'Event approved'), ('event_rejected', 'Event rejected'), ('event_needs_approval', 'Event needs approval'), ('hero_approved', 'Hero submission approved'), ('hero_rejected', 'Hero submission rejected'), ('hero_needs_approval', 'Hero submission needs approval'), ('order_status', 'Order status changed'), ('support_reply', 'Support reply'), ('new_message', 'New support message'), ('contact_message', 'New contact message')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.businessowner')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.customer')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.staffuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'is_read'], name='notificatio_custome_f9e80f_idx'), models.Index(fields=['business_owner', 'is_read'], name='notificatio_busines_f8455a_idx'), models.Index(fields=['staff', 'is_read'], name='notificatio_staff_i_e8b001_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('business_owner__isnull', True), ('customer__isnull', False), ('staff__isnull', True)), models.Q(('business_owner__isnull', False), ('customer__isnull', True), ('staff__isnull', True)), models.Q(('business_owner__isnull', True), ('customer__isnull', True), ('staff__isnull', False)), _connector='OR'), name='notification_exactly_one_recipient'),
        ),
    ]
