# Generated by Django 5.0.9 on 2026-10-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('kyc_approved', 'KYC approved'), ('kyc_rejected', 'KYC rejected'), ('kyc_needs_approval', 'KYC needs approval'), ('listing_approved', 'Listing approved'), ('listing_rejected', 'Listing rejected'), ('listing_needs_moderation', 'Listing needs moderation'), ('event_approved', 'Event approved'), ('event_rejected', 'Event rejected'), ('event_needs_approval', 'Event needs approval'), ('hero_approved', 'Hero submission approved'), ('hero_rejected', 'Hero submission rejected'), ('hero_needs_approval', 'Hero submission needs approval'), ('order_status', 'Order status changed'), ('new_order', 'New order'), ('support_reply', 'Support reply'), ('new_message', 'New support message'), ('contact_message', 'New contact message')], max_length=40),
        ),
    ]
