# Generated by Django 5.2.18 on 2026-10-08 03:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0037_seed_approvals_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Returned'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('stage', models.CharField(choices=[('manager', "The maker's manager"), ('pool', "Anyone holding the kind's permission"), ('super_admin', 'A Super Admin')], default='super_admin', max_length=12)),
                ('pool_permission', models.CharField(blank=True, default='', max_length=100)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_label', models.CharField(blank=True, default='', max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('maker_note', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('due_at', models.DateTimeField()),
                ('stage_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_level', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests_assigned', to='accounts.staffuser')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests_decided', to='accounts.staffuser')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests_made', to='accounts.staffuser')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'stage', 'due_at'], name='approvals_a_status_7e5019_idx'), models.Index(fields=['maker', 'status'], name='approvals_a_maker_i_67ac23_idx'), models.Index(fields=['assigned_to', 'status'], name='approvals_a_assigne_d284a6_idx')],
            },
        ),
    ]
