# Generated by Django 5.0.9 on 2026-07-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_subscription_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='boost_credits_per_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='hero_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_active_listings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
