# Generated by Django 5.0.9 on 2026-07-14 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_seed_hero_and_event_approve_permissions'),
        ('billing', '0004_backfill_subscription_plan_entitlements'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='business_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.businessowner'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('business_owner__isnull', False), ('customer__isnull', True)), models.Q(('business_owner__isnull', True), ('customer__isnull', False)), _connector='OR'), name='transaction_exactly_one_of_business_owner_or_customer'),
        ),
    ]
