# Generated by Django 5.0.9 on 2026-07-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_transaction_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='success', max_length=10),
        ),
    ]
