# Generated by Django 5.0.9 on 2026-07-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='kind',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending_approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_active_listings',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('product_basic', 'Product Basic'), ('product_unlimited', 'Product Unlimited'), ('service', 'Service')], max_length=20, unique=True),
        ),
    ]
