# Generated by Django 5.0.9 on 2026-07-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_subscriptionplan_approval_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cycle_months',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 month'), (3, '3 months'), (6, '6 months'), (12, '12 months')], default=1),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
