# Generated by Django 5.0.9 on 2026-07-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_backfill_cycle_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='billing_cycle',
        ),
    ]
