# Generated by Django 5.0.9 on 2026-07-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_remove_subscription_billing_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='annual_price',
        ),
    ]
