# Generated by Django 5.0.9 on 2026-07-15 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_delete_old_subscription_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]*$', 'Tier must be lowercase letters, numbers, and underscores only, starting with a letter.')]),
        ),
    ]
