# Generated by Django 5.0.9 on 2026-07-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_subscriptionplan_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='hero_slots',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
