# Generated by Django 5.2.18 on 2026-10-09 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0041_owner_claim_and_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('registration', 'Registration'), ('three_paid_months_bonus', '3-paid-months bonus')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('approval_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.staffuser')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.staffuser')),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommissionAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('registration', 'Registration'), ('three_paid_months_bonus', '3-paid-months bonus')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earned_at', models.DateTimeField()),
                ('hold_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('on_hold', 'On hold'), ('payable', 'Approved to pay'), ('in_batch', 'In a payout batch'), ('paid', 'Paid'), ('reversed', 'Reversed')], default='on_hold', max_length=10)),
                ('reversed_reason', models.CharField(blank=True, default='', max_length=40)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, default='', max_length=50)),
                ('source_id', models.CharField(blank=True, default='', max_length=64)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_accruals', to='accounts.businessowner')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_accruals', to='accounts.staffuser')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accruals', to='commission.commissionpolicy')),
            ],
            options={
                'ordering': ['-earned_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='commissionpolicy',
            index=models.Index(fields=['kind', '-effective_from'], name='commission__kind_18f46c_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionaccrual',
            index=models.Index(fields=['staff', '-earned_at'], name='commission__staff_i_08a1f2_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionaccrual',
            index=models.Index(fields=['status', 'hold_until'], name='commission__status_1dc1d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='commissionaccrual',
            constraint=models.UniqueConstraint(fields=('business_owner', 'kind'), name='commission_one_per_business_and_kind'),
        ),
    ]
