# Generated by Django 5.0.9 on 2026-07-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
