# Generated by Django 5.2.18 on 2026-10-09 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0041_owner_claim_and_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TargetLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('registrations', 'Registrations'), ('visits', 'Visits'), ('calls', 'Calls'), ('renewals', 'Renewals')], max_length=20, unique=True)),
                ('min_daily', models.PositiveIntegerField()),
                ('max_daily', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.staffuser')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdays', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.staffuser')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_pattern', to='accounts.staffuser')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('kind', models.CharField(choices=[('annual', 'Annual leave'), ('sick', 'Sick leave'), ('other', 'Other')], default='annual', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.staffuser')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='accounts.staffuser')),
            ],
            options={
                'ordering': ['-start', '-id'],
                'indexes': [models.Index(fields=['staff', 'start', 'end'], name='targets_lea_staff_i_a94f08_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end__gte', models.F('start'))), name='leave_end_not_before_start')],
            },
        ),
        migrations.CreateModel(
            name='TargetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('registrations', 'Registrations'), ('visits', 'Visits'), ('calls', 'Calls'), ('renewals', 'Renewals')], max_length=20)),
                ('daily_value', models.PositiveIntegerField()),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.staffuser')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_plans', to='accounts.staffuser')),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
                'indexes': [models.Index(fields=['staff', 'metric', '-effective_from'], name='targets_tar_staff_i_241627_idx')],
            },
        ),
    ]
