# Generated by Django 5.0.9 on 2026-07-12 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_businessownerprofile_business_reg_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=300)),
                ('factors', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('business_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_score', to='accounts.businessowner')),
            ],
        ),
    ]
