# Generated by Django 5.0.9 on 2026-07-17 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_seed_credit_manage_permission'),
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('partner_type', models.CharField(choices=[('bank', 'Bank'), ('microfinance', 'Microfinance'), ('ngo', 'NGO Lender'), ('government', 'Government Grant'), ('other', 'Other')], default='bank', max_length=20)),
                ('logo', models.CharField(blank=True, max_length=8)),
                ('color', models.CharField(blank=True, max_length=9)),
                ('min_score', models.PositiveIntegerField(default=300)),
                ('max_loan', models.CharField(blank=True, max_length=50)),
                ('interest_rate', models.CharField(blank=True, max_length=50)),
                ('turnaround', models.CharField(blank=True, max_length=50)),
                ('focus', models.CharField(blank=True, max_length=150)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['min_score', 'name'],
            },
        ),
        migrations.AddField(
            model_name='creditscore',
            name='adjusted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_credit_scores', to='accounts.staffuser'),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='adjustment_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='manual_adjustment',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(max_length=500)),
                ('score_at_application', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('declined', 'Declined')], default='submitted', max_length=20)),
                ('decision_notes', models.CharField(blank=True, max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='accounts.businessowner')),
                ('lending_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications', to='credit.lendingpartner')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loan_applications', to='accounts.staffuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
