# Generated by Django 5.2.18 on 2026-10-09 15:46

import accounts.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0041_owner_claim_and_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('prospecting', 'Prospecting'), ('registration', 'Registration'), ('onboarding_photos', 'Onboarding & photos'), ('subscription_follow_up', 'Subscription follow-up'), ('delivery_follow_up', 'Delivery follow-up'), ('info_update', 'Info update'), ('verification', 'Verification')], max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('abandoned', 'Abandoned')], default='open', max_length=10)),
                ('checked_in_at', models.DateTimeField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_m', models.PositiveIntegerField()),
                ('distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('outside_radius', models.BooleanField(default=False)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('out_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('out_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('out_accuracy_m', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('business_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='accounts.businessowner')),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='accounts.staffuser')),
                ('scout_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='accounts.scoutassignment')),
            ],
            options={
                'ordering': ['-checked_in_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VisitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='visit_photos/', validators=[accounts.validators.validate_image_content_type])),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy_m', models.PositiveIntegerField(blank=True, null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='field.visitcheckin')),
            ],
            options={
                'ordering': ['taken_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='visitcheckin',
            index=models.Index(fields=['scout', '-checked_in_at'], name='field_visit_scout_i_6b6b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='visitcheckin',
            index=models.Index(fields=['business_owner', '-checked_in_at'], name='field_visit_busines_40515c_idx'),
        ),
        migrations.AddConstraint(
            model_name='visitcheckin',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('scout',), name='one_open_visit_per_scout'),
        ),
    ]
