# Generated by Django 5.2.18 on 2026-10-09 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_owner_claim_and_consent'),
        ('field', '0001_initial'),
        ('listings', '0019_listing_created_by_staff'),
        ('staff_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy_m', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('interested', 'Interested'), ('follow_up', 'Follow up'), ('registered', 'Registered'), ('not_interested', 'Not interested')], default='new', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follow_up_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff_tasks.task')),
                ('registered_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_records', to='accounts.businessowner')),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospects', to='accounts.staffuser')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='listings.zone')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='visitcheckin',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='field.prospect'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['scout', 'status'], name='field_prosp_scout_i_ac7a80_idx'),
        ),
    ]
