# Generated by Django 5.2.18 on 2026-10-07 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0033_seed_activity_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, default='', max_length=50)),
                ('source_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.staffuser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.staffuser')),
            ],
            options={
                'ordering': ['due_at', 'id'],
                'indexes': [models.Index(fields=['owner', 'status', 'due_at'], name='staff_tasks_owner_i_0049ec_idx')],
            },
        ),
    ]
