# Generated by Django 5.2.18 on 2026-10-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField()),
                ('actor_type', models.CharField(choices=[('staff', 'Staff'), ('customer', 'Customer'), ('business_owner', 'Business owner'), ('system', 'System')], max_length=20)),
                ('actor_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('actor_role', models.CharField(blank=True, default='', max_length=20)),
                ('actor_label', models.CharField(blank=True, default='', max_length=150)),
                ('on_behalf_of_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('verb', models.CharField(max_length=100)),
                ('method', models.CharField(blank=True, default='', max_length=8)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_label', models.CharField(blank=True, default='', max_length=200)),
                ('summary', models.CharField(blank=True, default='', max_length=300)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('prev_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['actor_type', 'actor_id', '-occurred_at'], name='activity_ac_actor_t_c9146e_idx'), models.Index(fields=['actor_role', '-occurred_at'], name='activity_ac_actor_r_fe0852_idx'), models.Index(fields=['verb'], name='activity_ac_verb_cf2b70_idx'), models.Index(fields=['target_type', 'target_id'], name='activity_ac_target__0c7687_idx')],
            },
        ),
    ]
