# Generated by Django 5.2.18 on 2026-10-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_append_only_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='prev_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
