#!/usr/bin/env bash
#
# AshantiHub deploy. Run on the server as root:
#
#   bash /opt/ashantihub/infra/scripts/deploy.sh            # production
#   bash /opt/ashantihub-staging/infra/scripts/deploy.sh    # staging
#
# Which environment is deployed comes from the checkout's own .deploy.conf
# (untracked, written once when the server was provisioned) rather than from
# an argument, so a production deploy cannot be aimed at staging — or the
# reverse — by mistyping a flag.
#
# The database is dumped before migrations run. That dump is the rollback.
#
# Production (SERVE_FRONTEND=yes) also reinstalls the HestiaCP nginx templates
# when they differ from the last installed tree (recorded in the untracked
# .templates-installed marker; a missing marker reinstalls). Set FORCE_TEMPLATES
# to 1, yes or true (any case) to reinstall regardless:
#
#   FORCE_TEMPLATES=1 bash /opt/ashantihub/infra/scripts/deploy.sh
set -euo pipefail

# This script git-resets the very checkout it lives in, and bash reads a
# script incrementally by byte offset rather than loading it whole. Rewriting
# this file mid-run therefore makes bash resume at the wrong offset in the new
# contents and silently skip steps — which is exactly how the first deploy
# onto this server skipped its chown and failed in collectstatic. Re-exec from
# a copy outside the checkout so the running file can never change underfoot.
if [[ "${DEPLOY_REEXEC:-}" != "1" ]]; then
	_app_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
	_self_copy="$(mktemp /tmp/ashantihub-deploy.XXXXXXXX.sh)"
	cp "${BASH_SOURCE[0]}" "$_self_copy"
	export DEPLOY_REEXEC=1 DEPLOY_APP_DIR="$_app_dir" DEPLOY_SELF_COPY="$_self_copy"
	exec bash "$_self_copy" "$@"
fi

# Passed by the block above; the copy lives in /tmp, so it cannot derive this
# from its own location any more.
APP_DIR="${DEPLOY_APP_DIR:?internal: DEPLOY_APP_DIR not set}"
trap 'rm -f "${DEPLOY_SELF_COPY:-}"' EXIT

CONF="$APP_DIR/.deploy.conf"

[[ -f "$CONF" ]] || {
	echo "FATAL: $CONF not found — this checkout has not been provisioned." >&2
	exit 1
}
# shellcheck source=/dev/null
source "$CONF"
: "${ENV_NAME:?missing in .deploy.conf}"
: "${BRANCH:?missing in .deploy.conf}"
: "${PROJECT:?missing in .deploy.conf}"
: "${APP_PORT:?missing in .deploy.conf}"
: "${GUNICORN_WORKERS:?missing in .deploy.conf}"

[[ -f "$APP_DIR/backend/.env" ]] || {
	echo "FATAL: $APP_DIR/backend/.env not found — nothing to configure the app with." >&2
	exit 1
}

# Live updates and background jobs need these in every environment's .env.
# STAFF_SECRETS_KEY is first used by plan 1B Task 4.
_missing=()
grep -q '^REDIS_URL=redis' "$APP_DIR/backend/.env" || _missing+=("REDIS_URL")
grep -q '^REDIS_URL=.*PASTE_' "$APP_DIR/backend/.env" && _missing+=("REDIS_URL (still a PASTE_ placeholder)")
grep -q '^REDIS_PASSWORD=.' "$APP_DIR/backend/.env" || _missing+=("REDIS_PASSWORD")
grep -q '^STAFF_SECRETS_KEY=.' "$APP_DIR/backend/.env" || _missing+=("STAFF_SECRETS_KEY")
grep -q '^STAFF_SECRETS_KEY=.*PASTE_' "$APP_DIR/backend/.env" && _missing+=("STAFF_SECRETS_KEY (still a PASTE_ placeholder)")
if ((${#_missing[@]})); then
	echo "FATAL: $APP_DIR/backend/.env is missing or unset: ${_missing[*]} (see infra/env/backend.env.example)." >&2
	exit 1
fi

# Consumed by docker-compose.yml's ${APP_PORT} / ${GUNICORN_WORKERS}.
# The realtime (WebSocket) service listens 100 above the API: 8100 / 8101.
REALTIME_PORT=$((APP_PORT + 100))
export APP_PORT GUNICORN_WORKERS REALTIME_PORT

# Compose automatically reads a .env sitting next to the compose file, so
# writing this environment's values there makes a plain
# `docker compose -p <project> -f .../docker-compose.yml up -d` behave
# identically to a deploy. Without it such a command silently falls back to
# the ${APP_PORT:-8000} default — which publishes staging on production's
# port, or (as happened once) publishes nothing at all and 502s the site.
cat > "$APP_DIR/infra/compose/.env" <<ENVVARS
# Generated by deploy.sh from .deploy.conf — do not edit, not in git.
APP_PORT=$APP_PORT
GUNICORN_WORKERS=$GUNICORN_WORKERS
APP_IMAGE=$PROJECT-app
REALTIME_PORT=$REALTIME_PORT
ENVVARS
COMPOSE=(docker compose -p "$PROJECT" -f "$APP_DIR/infra/compose/docker-compose.yml")

log() { printf '\n\033[1;33m==> %s\033[0m\n' "$*"; }

# Marker recording which infra/hestia/templates/ tree was last installed into
# HestiaCP (untracked, written only after a successful install). Comparing
# against it, rather than diffing OLD_SHA..NEW_SHA, survives a failed deploy:
# the reset to origin/$BRANCH happens early, so on the retry OLD_SHA == NEW_SHA
# and a diff would silently skip templates that were never installed.
TEMPLATES_MARKER="$APP_DIR/.templates-installed"

# Succeeds (0) when the HestiaCP templates must be (re)installed: FORCE_TEMPLATES
# is 1/yes/true (any case), the marker is missing (safe default: the install is
# idempotent), or the marker differs from the current templates tree. Returns 1
# for "nothing to do". A git failure aborts the deploy rather than being read as
# "unchanged", which would silently ship a promotion without its nginx changes.
templates_changed() {
	case "${FORCE_TEMPLATES:-}" in
		1 | [Yy][Ee][Ss] | [Tt][Rr][Uu][Ee]) return 0 ;;
	esac
	local tree
	tree="$(git -C "$APP_DIR" rev-parse HEAD:infra/hestia/templates)" || {
		echo "FATAL: cannot resolve the infra/hestia/templates tree hash." >&2
		exit 1
	}
	[[ -f "$TEMPLATES_MARKER" && "$(cat "$TEMPLATES_MARKER")" == "$tree" ]] && return 1
	return 0
}

# Runs the installer and, only if it succeeds, records the installed tree.
install_templates() {
	bash "$APP_DIR/infra/scripts/install-hestia-templates.sh" || {
		echo "FATAL: nginx template install failed AFTER the app and frontend went live. nginx is still serving its previous config from memory, but the on-disk vhosts may now be invalid — do NOT reload nginx. Fix infra/hestia/templates/, then re-run this deploy (the missing/stale .templates-installed marker makes it reinstall automatically) or set FORCE_TEMPLATES=1." >&2
		exit 1
	}
	git -C "$APP_DIR" rev-parse HEAD:infra/hestia/templates >"$TEMPLATES_MARKER"
}

log "Deploying $ENV_NAME from origin/$BRANCH ($APP_DIR)"

log "Backing up the database"
bash "$APP_DIR/infra/scripts/backup-db.sh"

log "Fetching origin/$BRANCH"
git -C "$APP_DIR" fetch --prune origin
OLD_SHA="$(git -C "$APP_DIR" rev-parse --short HEAD)"
git -C "$APP_DIR" reset --hard "origin/$BRANCH"
NEW_SHA="$(git -C "$APP_DIR" rev-parse --short HEAD)"
echo "  $OLD_SHA -> $NEW_SHA"

log "Building the application image"
"${COMPOSE[@]}" build web

log "Starting the database and Redis"
"${COMPOSE[@]}" up -d db redis

# Compose only enforces service_healthy for services it starts as a
# dependency, so the one-off `run` calls below need their own wait.
log "Waiting for the database to accept connections"
for _ in $(seq 1 60); do
	if "${COMPOSE[@]}" exec -T db pg_isready -q 2>/dev/null; then break; fi
	sleep 2
done
"${COMPOSE[@]}" exec -T db pg_isready || {
	echo "FATAL: database did not become ready." >&2
	exit 1
}

# Must happen before collectstatic, not after: Docker creates a missing bind
# mount source root-owned, and the container runs as uid 10001, so the first
# collectstatic into a fresh staticfiles/ fails with EACCES otherwise.
log "Fixing ownership of the bind-mounted data directories"
mkdir -p "$APP_DIR/backend/media" "$APP_DIR/backend/staticfiles" "$APP_DIR/backend/private"
chown -R 10001:10001 "$APP_DIR/backend/media" "$APP_DIR/backend/staticfiles" "$APP_DIR/backend/private"

log "Applying migrations"
"${COMPOSE[@]}" run --rm --no-deps web python manage.py migrate --noinput

log "Collecting static files"
"${COMPOSE[@]}" run --rm --no-deps web python manage.py collectstatic --noinput

log "Starting the application"
"${COMPOSE[@]}" up -d web

log "Waiting for the API to answer"
for _ in $(seq 1 45); do
	if curl -fsS -H 'X-Forwarded-Proto: https' "http://127.0.0.1:$APP_PORT/api/health/" >/dev/null 2>&1; then
		echo "  API healthy on 127.0.0.1:$APP_PORT"
		break
	fi
	sleep 2
done
curl -fsS -H 'X-Forwarded-Proto: https' "http://127.0.0.1:$APP_PORT/api/health/" >/dev/null || {
	echo "FATAL: API did not come up. Recent logs:" >&2
	"${COMPOSE[@]}" logs --tail=60 web >&2
	exit 1
}

if [[ "${SERVE_FRONTEND:-no}" == "yes" ]]; then
	: "${WEB_ROOT:?SERVE_FRONTEND=yes requires WEB_ROOT in .deploy.conf}"
	: "${WEB_USER:?SERVE_FRONTEND=yes requires WEB_USER in .deploy.conf}"

	log "Building the frontend"
	# Built in a container so the host needs no Node toolchain. Vite reads
	# frontend/.env.production for VITE_API_BASE_URL.
	docker run --rm \
		-v "$APP_DIR/frontend":/app \
		-w /app \
		node:20-alpine \
		sh -c "npm ci --no-audit --no-fund && npm run build"

	log "Publishing the frontend to $WEB_ROOT"
	mkdir -p "$WEB_ROOT"
	rsync -a --delete "$APP_DIR/frontend/dist/" "$WEB_ROOT/"
	chown -R "$WEB_USER":"$WEB_USER" "$WEB_ROOT"

	# Templates only take effect once installed into HestiaCP, so a template
	# change (e.g. the no-cache headers for /sw.js) would otherwise ship silently
	# inert. This lives in the SERVE_FRONTEND branch on purpose: the installer
	# copies the SPA templates from whichever checkout runs it and rebuilds every
	# domain, so running it from staging (whose frontend is on Vercel) would push
	# unreleased templates onto the production domain.
	if templates_changed; then
		log "Reinstalling HestiaCP nginx templates (changed since the last install)"
		install_templates
	else
		log "HestiaCP nginx templates unchanged; skipping reinstall"
	fi
fi

# Only now, with the API healthy and the frontend that matches it published,
# start the live-update and background-job processes. A fault in any of them
# fails the deploy here, after sign-in and the public site already work on
# the new release — never between the new API and its frontend.
log "Starting the realtime service, worker and scheduler"
"${COMPOSE[@]}" up -d realtime worker beat

log "Waiting for the realtime service to answer"
for _ in $(seq 1 45); do
	if curl -fsS -H 'X-Forwarded-Proto: https' "http://127.0.0.1:$REALTIME_PORT/api/health/" >/dev/null 2>&1; then
		echo "  realtime healthy on 127.0.0.1:$REALTIME_PORT"
		break
	fi
	sleep 2
done
curl -fsS -H 'X-Forwarded-Proto: https' "http://127.0.0.1:$REALTIME_PORT/api/health/" >/dev/null || {
	echo "FATAL: the realtime service did not come up. Recent logs:" >&2
	"${COMPOSE[@]}" logs --tail=60 realtime >&2
	exit 1
}

log "Waiting for the background worker"
for _ in $(seq 1 30); do
	if "${COMPOSE[@]}" exec -T worker celery -A ashantihub inspect ping --timeout 5 >/dev/null 2>&1; then
		echo "  worker answering"
		break
	fi
	sleep 2
done
"${COMPOSE[@]}" exec -T worker celery -A ashantihub inspect ping --timeout 5 >/dev/null || {
	echo "FATAL: the Celery worker did not answer. Recent logs:" >&2
	"${COMPOSE[@]}" logs --tail=60 worker >&2
	exit 1
}

log "Removing unused images"
docker image prune -f >/dev/null

log "Deployed $ENV_NAME: $OLD_SHA -> $NEW_SHA"
"${COMPOSE[@]}" ps
