#!/usr/bin/env bash
#
# AshantiHub deploy. Run on the server as root:
#
#   bash /opt/ashantihub/infra/scripts/deploy.sh            # production
#   bash /opt/ashantihub-staging/infra/scripts/deploy.sh    # staging
#
# Which environment is deployed comes from the checkout's own .deploy.conf
# (untracked, written once when the server was provisioned) rather than from
# an argument, so a production deploy cannot be aimed at staging — or the
# reverse — by mistyping a flag.
#
# The database is dumped before migrations run. That dump is the rollback.
#
# Production (SERVE_FRONTEND=yes) also reinstalls the HestiaCP nginx templates
# when infra/hestia/templates/ changed in this deploy. Set FORCE_TEMPLATES=1 to
# reinstall them regardless:
#
#   FORCE_TEMPLATES=1 bash /opt/ashantihub/infra/scripts/deploy.sh
set -euo pipefail

# This script git-resets the very checkout it lives in, and bash reads a
# script incrementally by byte offset rather than loading it whole. Rewriting
# this file mid-run therefore makes bash resume at the wrong offset in the new
# contents and silently skip steps — which is exactly how the first deploy
# onto this server skipped its chown and failed in collectstatic. Re-exec from
# a copy outside the checkout so the running file can never change underfoot.
if [[ "${DEPLOY_REEXEC:-}" != "1" ]]; then
	_app_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
	_self_copy="$(mktemp /tmp/ashantihub-deploy.XXXXXXXX.sh)"
	cp "${BASH_SOURCE[0]}" "$_self_copy"
	export DEPLOY_REEXEC=1 DEPLOY_APP_DIR="$_app_dir" DEPLOY_SELF_COPY="$_self_copy"
	exec bash "$_self_copy" "$@"
fi

# Passed by the block above; the copy lives in /tmp, so it cannot derive this
# from its own location any more.
APP_DIR="${DEPLOY_APP_DIR:?internal: DEPLOY_APP_DIR not set}"
trap 'rm -f "${DEPLOY_SELF_COPY:-}"' EXIT

CONF="$APP_DIR/.deploy.conf"

[[ -f "$CONF" ]] || {
	echo "FATAL: $CONF not found — this checkout has not been provisioned." >&2
	exit 1
}
# shellcheck source=/dev/null
source "$CONF"
: "${ENV_NAME:?missing in .deploy.conf}"
: "${BRANCH:?missing in .deploy.conf}"
: "${PROJECT:?missing in .deploy.conf}"
: "${APP_PORT:?missing in .deploy.conf}"
: "${GUNICORN_WORKERS:?missing in .deploy.conf}"

[[ -f "$APP_DIR/backend/.env" ]] || {
	echo "FATAL: $APP_DIR/backend/.env not found — nothing to configure the app with." >&2
	exit 1
}

# Consumed by docker-compose.yml's ${APP_PORT} / ${GUNICORN_WORKERS}.
export APP_PORT GUNICORN_WORKERS

# Compose automatically reads a .env sitting next to the compose file, so
# writing this environment's values there makes a plain
# `docker compose -p <project> -f .../docker-compose.yml up -d` behave
# identically to a deploy. Without it such a command silently falls back to
# the ${APP_PORT:-8000} default — which publishes staging on production's
# port, or (as happened once) publishes nothing at all and 502s the site.
cat > "$APP_DIR/infra/compose/.env" <<ENVVARS
# Generated by deploy.sh from .deploy.conf — do not edit, not in git.
APP_PORT=$APP_PORT
GUNICORN_WORKERS=$GUNICORN_WORKERS
ENVVARS
COMPOSE=(docker compose -p "$PROJECT" -f "$APP_DIR/infra/compose/docker-compose.yml")

log() { printf '\n\033[1;33m==> %s\033[0m\n' "$*"; }

# Succeeds (0) when the HestiaCP templates must be reinstalled: FORCE_TEMPLATES=1,
# or infra/hestia/templates/ differs between the old and new checkout. Returns 1
# for "nothing to do". A git failure aborts the deploy rather than being read as
# "unchanged", which would silently ship a promotion without its nginx changes.
templates_changed() {
	[[ "${FORCE_TEMPLATES:-}" == "1" ]] && return 0
	# First deploy / nothing pulled: there is no range to diff.
	[[ "$OLD_SHA" == "$NEW_SHA" ]] && return 1
	local rc=0
	git -C "$APP_DIR" diff --quiet "$OLD_SHA" "$NEW_SHA" -- infra/hestia/templates/ || rc=$?
	case "$rc" in
		0) return 1 ;;
		1) return 0 ;;
		*)
			echo "FATAL: git diff of infra/hestia/templates/ failed (status $rc)." >&2
			exit 1
			;;
	esac
}

log "Deploying $ENV_NAME from origin/$BRANCH ($APP_DIR)"

log "Backing up the database"
bash "$APP_DIR/infra/scripts/backup-db.sh"

log "Fetching origin/$BRANCH"
git -C "$APP_DIR" fetch --prune origin
OLD_SHA="$(git -C "$APP_DIR" rev-parse --short HEAD)"
git -C "$APP_DIR" reset --hard "origin/$BRANCH"
NEW_SHA="$(git -C "$APP_DIR" rev-parse --short HEAD)"
echo "  $OLD_SHA -> $NEW_SHA"

log "Building the application image"
"${COMPOSE[@]}" build web

log "Starting the database"
"${COMPOSE[@]}" up -d db

# Compose only enforces service_healthy for services it starts as a
# dependency, so the one-off `run` calls below need their own wait.
log "Waiting for the database to accept connections"
for _ in $(seq 1 60); do
	if "${COMPOSE[@]}" exec -T db pg_isready -q 2>/dev/null; then break; fi
	sleep 2
done
"${COMPOSE[@]}" exec -T db pg_isready || {
	echo "FATAL: database did not become ready." >&2
	exit 1
}

# Must happen before collectstatic, not after: Docker creates a missing bind
# mount source root-owned, and the container runs as uid 10001, so the first
# collectstatic into a fresh staticfiles/ fails with EACCES otherwise.
log "Fixing ownership of the bind-mounted data directories"
mkdir -p "$APP_DIR/backend/media" "$APP_DIR/backend/staticfiles"
chown -R 10001:10001 "$APP_DIR/backend/media" "$APP_DIR/backend/staticfiles"

log "Applying migrations"
"${COMPOSE[@]}" run --rm --no-deps web python manage.py migrate --noinput

log "Collecting static files"
"${COMPOSE[@]}" run --rm --no-deps web python manage.py collectstatic --noinput

log "Starting the application"
"${COMPOSE[@]}" up -d web

log "Waiting for the API to answer"
for _ in $(seq 1 45); do
	if curl -fsS -H 'X-Forwarded-Proto: https' "http://127.0.0.1:$APP_PORT/api/health/" >/dev/null 2>&1; then
		echo "  API healthy on 127.0.0.1:$APP_PORT"
		break
	fi
	sleep 2
done
curl -fsS -H 'X-Forwarded-Proto: https' "http://127.0.0.1:$APP_PORT/api/health/" >/dev/null || {
	echo "FATAL: API did not come up. Recent logs:" >&2
	"${COMPOSE[@]}" logs --tail=60 web >&2
	exit 1
}

if [[ "${SERVE_FRONTEND:-no}" == "yes" ]]; then
	: "${WEB_ROOT:?SERVE_FRONTEND=yes requires WEB_ROOT in .deploy.conf}"
	: "${WEB_USER:?SERVE_FRONTEND=yes requires WEB_USER in .deploy.conf}"

	log "Building the frontend"
	# Built in a container so the host needs no Node toolchain. Vite reads
	# frontend/.env.production for VITE_API_BASE_URL.
	docker run --rm \
		-v "$APP_DIR/frontend":/app \
		-w /app \
		node:20-alpine \
		sh -c "npm ci --no-audit --no-fund && npm run build"

	log "Publishing the frontend to $WEB_ROOT"
	mkdir -p "$WEB_ROOT"
	rsync -a --delete "$APP_DIR/frontend/dist/" "$WEB_ROOT/"
	chown -R "$WEB_USER":"$WEB_USER" "$WEB_ROOT"

	# Templates only take effect once installed into HestiaCP, so a template
	# change (e.g. the no-cache headers for /sw.js) would otherwise ship silently
	# inert. This lives in the SERVE_FRONTEND branch on purpose: the installer
	# copies the SPA templates from whichever checkout runs it and rebuilds every
	# domain, so running it from staging (whose frontend is on Vercel) would push
	# unreleased templates onto the production domain.
	if templates_changed; then
		log "Reinstalling HestiaCP nginx templates (changed in this deploy)"
		bash "$APP_DIR/infra/scripts/install-hestia-templates.sh"
	else
		log "HestiaCP nginx templates unchanged; skipping reinstall"
	fi
fi

log "Removing unused images"
docker image prune -f >/dev/null

log "Deployed $ENV_NAME: $OLD_SHA -> $NEW_SHA"
"${COMPOSE[@]}" ps
