# Generated by Django 5.0.9 on 2026-07-15 03:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_seed_reviews_moderate_permission'),
        ('events', '0002_event_capacity_eventrsvp'),
        ('listings', '0013_listing_service_duration_listing_specs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('listing', 'Listing'), ('event', 'Event'), ('seller', 'Seller'), ('organizer', 'Organizer')], max_length=10)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('published', 'Published'), ('hidden', 'Hidden')], default='published', max_length=10)),
                ('hidden_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to='accounts.customer')),
                ('business_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='accounts.businessowner')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.event')),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_reviews', to='accounts.staffuser')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listing')),
                ('organizer_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer_reviews_received', to='accounts.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('business_owner__isnull', True), ('event__isnull', True), ('listing__isnull', False), ('organizer_customer__isnull', True), ('target_type', 'listing')), models.Q(('business_owner__isnull', True), ('event__isnull', False), ('listing__isnull', True), ('organizer_customer__isnull', True), ('target_type', 'event')), models.Q(('business_owner__isnull', False), ('event__isnull', True), ('listing__isnull', True), ('organizer_customer__isnull', True), ('target_type', 'seller')), models.Q(('business_owner__isnull', False), ('event__isnull', True), ('listing__isnull', True), ('organizer_customer__isnull', True), ('target_type', 'organizer')), models.Q(('business_owner__isnull', True), ('event__isnull', True), ('listing__isnull', True), ('organizer_customer__isnull', False), ('target_type', 'organizer')), _connector='OR'), name='review_exactly_one_target_matching_type'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('listing__isnull', False)), fields=('author', 'listing'), name='unique_review_per_author_listing'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False)), fields=('author', 'event'), name='unique_review_per_author_event'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('business_owner__isnull', False)), fields=('author', 'business_owner', 'target_type'), name='unique_review_per_author_business_owner_target_type'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('organizer_customer__isnull', False)), fields=('author', 'organizer_customer'), name='unique_review_per_author_organizer_customer'),
        ),
    ]
