# Generated by Django 5.0.9 on 2026-07-16 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0020_passwordresettoken'),
        ('billing', '0015_alter_subscriptionplan_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='hubtel', max_length=20)),
                ('raw_payload', models.JSONField()),
                ('signature_valid', models.BooleanField(default=False)),
                ('hubtel_reference', models.CharField(blank=True, db_index=True, max_length=128)),
                ('processed', models.BooleanField(default=False)),
                ('processing_note', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('order_checkout', 'Order Checkout'), ('event_pay', 'Event Pay'), ('ticket_purchase', 'Ticket Purchase'), ('subscription', 'Subscription'), ('hero_extend', 'Hero Extend'), ('listing_promotion', 'Listing Promotion')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('provider', models.CharField(default='simulated', max_length=20)),
                ('hubtel_checkout_id', models.CharField(blank=True, max_length=128, null=True)),
                ('checkout_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='accounts.businessowner')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='accounts.customer')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='billing.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('business_owner__isnull', False), ('customer__isnull', True)), models.Q(('business_owner__isnull', True), ('customer__isnull', False)), _connector='OR'), name='checkout_session_exactly_one_of_business_owner_or_customer'),
        ),
    ]
