# Generated by Django 5.0.9 on 2026-07-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_checkoutsession_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='kind',
            field=models.CharField(choices=[('order_checkout', 'Order Checkout'), ('event_pay', 'Event Pay'), ('ticket_purchase', 'Ticket Purchase'), ('subscription', 'Subscription'), ('hero_extend', 'Hero Extend'), ('listing_promotion', 'Listing Promotion'), ('service_request', 'Service Request'), ('booking', 'Booking'), ('event_renew', 'Event Renewal')], max_length=20),
        ),
    ]
