# Generated by Django 5.0.9 on 2026-07-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_seed_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
