# Generated by Django 5.0.9 on 2026-07-10 13:58

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listingphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='listing_photos/main/', validators=[accounts.validators.validate_image_content_type]),
        ),
        migrations.AlterField(
            model_name='listingphoto',
            name='image',
            field=models.ImageField(upload_to='listing_photos/gallery/', validators=[accounts.validators.validate_image_content_type]),
        ),
    ]
