# Generated by Django 5.0.9 on 2026-07-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_main_photo_alter_listingphoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('event', 'Event')], default='product', max_length=10),
        ),
    ]
