# Generated by Django 5.0.9 on 2026-07-14 12:49

import accounts.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_seed_hero_and_event_approve_permissions'),
        ('listings', '0009_backfill_category_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroMediaSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(upload_to='hero_media/', validators=[accounts.validators.validate_image_content_type])),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('caption', models.CharField(max_length=140)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('extended_days', models.PositiveIntegerField(default=0)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_media_submissions', to='accounts.businessowner')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
