# Generated by Django 5.0.9 on 2026-07-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_seed_event_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='service_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='specs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
