# Generated by Django 5.0.9 on 2026-07-17 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_businessowner_reviewed_at_businessowner_reviewed_by_and_more'),
        ('listings', '0014_listing_brand_listing_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heromediasubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heromediasubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_hero_submissions', to='accounts.staffuser'),
        ),
        migrations.AddField(
            model_name='listing',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_listings', to='accounts.staffuser'),
        ),
    ]
