# Generated by Django 5.0.9 on 2026-07-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_heromediasubmission_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_accommodation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='units_total',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
