# Generated by Django 5.0.9 on 2026-07-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_category_is_accommodation_listing_units_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
