# Generated by Django 5.0.9 on 2026-07-18 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_promotion_rejection_reason_alter_promotion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='heromediasubmission',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_submissions', to='listings.listing'),
        ),
    ]
