# Generated by Django 5.0.9 on 2026-07-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_passwordresettoken'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='conversation_exactly_one_of_customer_or_business_owner',
        ),
        migrations.AddField(
            model_name='conversation',
            name='guest_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('business_owner', 'Business Owner'), ('staff', 'Staff'), ('guest', 'Guest')], max_length=15),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('business_owner__isnull', True), ('customer__isnull', False), ('guest_token__isnull', True)), models.Q(('business_owner__isnull', False), ('customer__isnull', True), ('guest_token__isnull', True)), models.Q(('business_owner__isnull', True), ('customer__isnull', True), ('guest_token__isnull', False)), _connector='OR'), name='conversation_exactly_one_starter'),
        ),
    ]
