# Generated by Django 5.0.9 on 2026-07-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_site_settings_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='service_dispute_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='warranty_returns_policy',
            field=models.TextField(blank=True),
        ),
    ]
